package Pesa;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime;  
import java.util.Date;
/**
 *
 * @author Ravinder's PC
 */
public class Credit extends javax.swing.JFrame {
    private final Expense UserBal;
    public void setUserBal(String s)//, Double b)
    {
        this.UserBal.setName(s);
        //this.UserBal.setInc(b);
    }
    /*public void setUserBal(Double b)
    {
        this.UserBal.setBal(b);
    }*/
    public void setUserBalName(String s)
    {
        this.UserBal.setName(s);
    }
    /**
     * Creates new form Credit
     */
    public Credit() {
        initComponents();
        UserBal = new Expense();
        Toolkit tk=Toolkit.getDefaultToolkit();
        int sht=(int)tk.getScreenSize().getHeight();
        int swd=(int)tk.getScreenSize().getWidth();
        int ht=350;
        int wd=450;
        int x=swd-wd;
        int y=sht-ht;
        this.setBounds(x/2, y/2, wd, ht);
        this.setTitle("Expense Manager");//*/
    }
    //@override
    /*public Credit(String s, Double b)
    {
        initComponents();
        this.setUserBal(s, b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        IncAmount = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        CancelB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ReasonCB = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        IncDes = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DateC = new com.toedter.calendar.JDateChooser();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Income Amt");

        IncAmount.setText("0");

        jButton1.setText("Add Income");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CancelB.setText("Cancel");
        CancelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBActionPerformed(evt);
            }
        });

        jLabel2.setText("Income Source");

        ReasonCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monthly Income", "Gift/Prize", "Scholarship", "Stipend", "Friend returned", "Other" }));
        ReasonCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReasonCBActionPerformed(evt);
            }
        });

        jLabel3.setText("Description");

        jLabel4.setText("Income Date");

        DateC.setDateFormatString("MMMMMMMMMMMM d, yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelB, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IncAmount)
                            .addComponent(IncDes)
                            .addComponent(DateC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ReasonCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IncAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReasonCB, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IncDes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DateC, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelB, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Double cred = Double.parseDouble(IncAmount.getText());
        //Have to get income of that month and increase it :
        //Month can be taken using DATECHOOSER;
        
        Date Date= DateC.getDate();
        SimpleDateFormat spf = new SimpleDateFormat("MMMM");
        String mon= spf.format(Date);
        spf = new SimpleDateFormat("YYYY");
        Date= DateC.getDate();
        String year = spf.format(Date);
        Date= DateC.getDate();
        spf = new SimpleDateFormat("dd MMM YYYY");
        String date = spf.format(Date);
        ResultSet rs;
        //UserBal.credit(cred);
        try{
            if(cred != 0){
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/expensemanager3","root","password");
            Statement stmt = conn.createStatement();
            String sql = "Select `Income` from usersmonth where `UID` = '"+UserBal.getName()+"' AND `Month` = '"+mon+"' AND `Year` = '"+year+"';";
            rs = stmt.executeQuery(sql);
            if(rs.next())
                    UserBal.setInc(rs.getDouble("Income"));
            else{
                String sql1 = "INSERT INTO usersmonth VALUES ('"+UserBal.getName() +"','"+ mon+"','"+ year +"','0','0'); ";
                stmt = conn.createStatement();
                stmt.executeUpdate(sql1);
                UserBal.setInc(0);
            }
            UserBal.credit(cred);
            String query = "Update usersmonth set `Income` = '"+Double.toString(UserBal.getInc())+"' where `UID` = '"+UserBal.getName()+"' AND `Month`='"+mon+"' AND `Year` = '"+year+"';";
            stmt.executeUpdate(query);
            /*query = "Select `Balance` from users where `UID` = '"+UserBal.getName()+"';";
            rs = stmt.executeQuery(query);
            rs.next();
            this.setUserBal(UserBal.getName(), rs.getDouble("Balance"));
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");  
            LocalDateTime now = LocalDateTime.now(); */ 
            //System.out.println(dtf.format(now)); 
            query = "insert into `transactions` (`UID`,`Month`,`Year`,`Type`,`Amount`,`Reason`,`Description`,`Date`) values ('"+UserBal.getName()+"','"+mon+"','"+year+"','INCOME','"+cred+"','"+ReasonCB.getSelectedItem().toString()+"','"+IncDes.getText()+"','"+date+"');";
            stmt.executeUpdate(query);
            stmt.close();
            conn.close();
            }
            LoggedIn loggedin = new LoggedIn();
            loggedin.show();
            loggedin.setUser(UserBal.getName());
            //loggedin.setExpenseL(Double.toString(UserBal.getBal()));
            this.dispose();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }//*/
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CancelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBActionPerformed
        // TODO add your handling code here:
        LoggedIn loggedin = new LoggedIn();
        loggedin.show();
        loggedin.setUser(UserBal.getName());
        //loggedin.setExpenseL(Double.toString(UserBal.getBal()));
        this.dispose();
    }//GEN-LAST:event_CancelBActionPerformed

    private void ReasonCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReasonCBActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ReasonCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Credit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Credit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Credit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Credit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Credit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelB;
    private com.toedter.calendar.JDateChooser DateC;
    private javax.swing.JTextField IncAmount;
    private javax.swing.JTextField IncDes;
    private javax.swing.JComboBox<String> ReasonCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
