package Pesa;


import java.awt.Color;
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ravinder's PC
 */
public final class LoggedIn extends javax.swing.JFrame {
    
    //private Expense UserBal;
    /*private void setUserBal(String s, Double b)
    {
        this.UserBal.setName(s);
        this.UserBal.setBal(b);
        this.setUser(s);
        this.setExpenseL(Double.toString(b));
    }*/
    public String InttoMonth(int a)
    {
        a++;
        String s="";
        switch (a)
        {
            case 1: s="January";
            break;
            case 2: s= "February";
            break;
            case 3: s= "March";
            break;
            case 4: s="April";
            break;
            case 5: s="May";
            break;
            case 6: s="June";
            break;
            case 7: s="July";
            break;
            case 8: s="August";
            break;
            case 9: s="September";
            break;
            case 10: s="October";
            break;
            case 11: s="November";
            break;
            case 12: s="December";
            break;
            
        }
        return s;
    }
    public void setUser(String s)
    {
        UserL.setText(s);
    }
    public void setExpenseL(String s)
    {
        ExpenseL.setText(s);
    }
    public void setIncomeL(String s)
    {
        IncomeL.setText(s);
    }
    public void setOverAllL(String s)
    {
        OverAllL.setText(s);
    }
    private void setLabels()
    {
        Connection con;
        Statement stmt;
        ResultSet rs;
        try
        {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/expensemanager3","root","password");
            stmt = con.createStatement();
            String sql = "Select `Expense`,`Income` from usersmonth where `UID`='"+UserL.getText()+"' AND `Month` = '"+InttoMonth(MonthL.getMonth())+"' AND `Year`='"+Integer.toString(YearL.getYear())+"';";
            rs = stmt.executeQuery(sql);
            if(rs.next()){
            Double income = rs.getDouble("Income");
            Double expense = rs.getDouble("Expense");
            ExpenseL.setText(Double.toString(expense));
            IncomeL.setText(Double.toString(income));
            Double overall = income+expense;
            if(overall>=0)
                OverAllL.setForeground(Color.GREEN);
            else
                OverAllL.setForeground(Color.RED);
            OverAllL.setText(Double.toString(overall));
            }
            else{
                ExpenseL.setText("0");
                IncomeL.setText("0");
                OverAllL.setText("0");
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    /**
     * Creates new form LoggedIn
     */
    public LoggedIn() {
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
        int sht=(int)tk.getScreenSize().getHeight();
        int swd=(int)tk.getScreenSize().getWidth();
        int ht=450;
        int wd=650;
        int x=swd-wd;
        int y=sht-ht;
        this.setBounds(x/2, y/2, wd, ht);
        this.setTitle("Expense Manager");//*/
        this.setLabels();
    }
    //@Override
    /*public LoggedIn(String s,Double b)
    {
        initComponents();
        this.setUserBal(s, b);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ExpenseL = new javax.swing.JLabel();
        CreditB = new javax.swing.JButton();
        DebitB = new javax.swing.JButton();
        UserL = new javax.swing.JLabel();
        LogOut = new javax.swing.JButton();
        TransB = new javax.swing.JButton();
        IncomeL = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        OverAllL = new javax.swing.JLabel();
        MonthL = new com.toedter.calendar.JMonthChooser();
        YearL = new com.toedter.calendar.JYearChooser();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Total Expense");

        ExpenseL.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        ExpenseL.setForeground(new java.awt.Color(255, 0, 0));
        ExpenseL.setText("0");

        CreditB.setText("Add Income");
        CreditB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditBActionPerformed(evt);
            }
        });

        DebitB.setText("Add Expense");
        DebitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DebitBActionPerformed(evt);
            }
        });

        UserL.setFont(new java.awt.Font("PMingLiU-ExtB", 3, 24)); // NOI18N
        UserL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Welcome", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 204, 0))); // NOI18N

        LogOut.setText("LogOut!");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });

        TransB.setText("Transactions History");
        TransB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransBActionPerformed(evt);
            }
        });

        IncomeL.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        IncomeL.setForeground(new java.awt.Color(0, 204, 0));
        IncomeL.setText("0");

        jLabel2.setText("Total Income");

        jLabel3.setText("Over All");

        OverAllL.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        OverAllL.setText("0");

        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Show For this Month");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(CreditB, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DebitB)
                .addGap(127, 127, 127))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(TransB)
                        .addGap(262, 262, 262)
                        .addComponent(LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OverAllL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IncomeL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ExpenseL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(UserL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(MonthL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(YearL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(YearL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MonthL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1)))
                    .addComponent(UserL, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ExpenseL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IncomeL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(OverAllL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DebitB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreditB, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TransB, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreditBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditBActionPerformed
        // TODO add your handling code here:
        Credit creditF = new Credit();
        creditF.show();
        creditF.setUserBal(UserL.getText());//,Double.parseDouble(ExpenseL.getText()));
        //creditF.setUserBalName(User.getText());
        this.dispose();
    }//GEN-LAST:event_CreditBActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
        new UserLogin().show();
        this.dispose();
    }//GEN-LAST:event_LogOutActionPerformed

    private void DebitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DebitBActionPerformed
        // TODO add your handling code here:
        Debit debitF = new Debit();
        debitF.show();
        debitF.setUserBal(UserL.getText());//,Double.parseDouble(ExpenseL.getText()));
        //debitF.setUserBalName(User.getText());
        this.dispose();
    }//GEN-LAST:event_DebitBActionPerformed

    private void TransBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransBActionPerformed
        // TODO add your handling code here:
        Transactions TransF = new Transactions();
        TransF.show();
        TransF.setUserT(UserL.getText());//, Double.parseDouble(ExpenseL.getText()));
        TransF.setUserL(UserL.getText());
        try
        {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/expensemanager3","root","password");
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("select `Type`,`Amount`,`Reason`,`Description`,`Date` from transactions where `UID` = '"+UserL.getText()+"' AND `Month` = '"+InttoMonth(MonthL.getMonth())+"' AND `Year`='"+Integer.toString(YearL.getYear())+"';");
            TransF.setTableContent(rs);
                        
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        this.dispose();
    }//GEN-LAST:event_TransBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection con;
        Statement stmt;
        ResultSet rs;
        try
        {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/expensemanager3","root","password");
            stmt = con.createStatement();
            String sql = "Select `Expense`,`Income` from usersmonth where `UID`='"+UserL.getText()+"' AND `Month` = '"+InttoMonth(MonthL.getMonth())+"' AND `Year`='"+Integer.toString(YearL.getYear())+"';";
            rs = stmt.executeQuery(sql);
            if(!rs.next()){
                JOptionPane.showMessageDialog(this,"No Expenses Or Income for This month!");
                ExpenseL.setText("0");
                IncomeL.setText("0");
                OverAllL.setText("0");
            }
            else{
                Double income = rs.getDouble("Income");
                Double expense = rs.getDouble("Expense");
                ExpenseL.setText(Double.toString(expense));
                IncomeL.setText(Double.toString(income));
                Double overall = income+expense;
                if(overall>=0)
                    OverAllL.setForeground(Color.GREEN);
                else
                    OverAllL.setForeground(Color.RED);
                OverAllL.setText(Double.toString(overall));
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoggedIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoggedIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoggedIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoggedIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoggedIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreditB;
    private javax.swing.JButton DebitB;
    private javax.swing.JLabel ExpenseL;
    private javax.swing.JLabel IncomeL;
    private javax.swing.JButton LogOut;
    private com.toedter.calendar.JMonthChooser MonthL;
    private javax.swing.JLabel OverAllL;
    private javax.swing.JButton TransB;
    private javax.swing.JLabel UserL;
    private com.toedter.calendar.JYearChooser YearL;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
/*
Connection con;
        Statement stmt;
        ResultSet rs;
        try
        {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/expensemanager3","root","Mnnit@17");
            stmt = con.createStatement();
            String sql = "Select `Expense`,`Income`,`Overall` from users where `UID`='"+UserL.getText()+"' AND `Month` = '"+MonthL.getSelectedItem().toString()+"';";
            rs = stmt.executeQuery(sql);
            rs.next();
            ExpenseL.setText(Double.toString(rs.getDouble("Expense")));
            IncomeL.setText(Double.toString(rs.getDouble("Income")));
            OverAllL.setText(Double.toString(rs.getDouble("Overall")));
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
*/
